
# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

[[constraint]]
  version = "v1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"

[[constraint]]
  version = "v0.0.7"
  name = "github.com/katzenpost/core"

[[constraint]]
  version = "v0.0.8"
  name = "github.com/katzenpost/authority"

[[override]]
  version = "v0.0.5"
  name = "github.com/katzenpost/minclient"

[[override]]
  revision = "fa2bd0d7fb55d8f0fa2cea8eb1d61c37c9df1b66"
  name = "github.com/katzenpost/client"

[[override]]
  version = "v0.0.7"
  name = "github.com/katzenpost/server"

# other stuff

[[override]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[override]]
  name = "github.com/abiosoft/ishell"
  version = "2.0.0"

[[override]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[override]]
  name = "github.com/ugorji/go"
  version = "1.1.1"

[[override]]
  revision = "a1dbeea552b7c8df4b542c66073e393de198a800"
  name = "github.com/hpcloud/tail"

[prune]
  go-tests = true
  unused-packages = true
